/**
 * workers/integrations/connectors/slack.js — Slack Connector
 * Native Slack Block Kit card generation and delivery for Alerts & Digests.
 */

export class SlackConnector {
  /**
   * Builds Slack Block Kit payload for an instant alert
   */
  static buildAlertPayload(article, ruleName = 'Keyword Match') {
    const title = (article.title || 'Untitled Article').replace(/[<>&]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[c]));
    const url = article.url || article.link || 'https://feedometer.com';
    const source = article.source_name || article.source || article.domain || 'FeedOmeter Intelligence';
    const snippet = (article.snippet || article.description || '').replace(/<[^>]+>/g, '').trim().slice(0, 200);
    const img = article.lead_image_url || article.image_url || article.image || '';

    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `⚡ Feed Alert: ${ruleName}`,
          emoji: true
        }
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*<${url}|${title}>*\n*${source}* • ${snippet ? `_${snippet}..._` : ''}`
        }
      }
    ];

    if (img && (img.startsWith('http://') || img.startsWith('https://'))) {
      blocks[1].accessory = {
        type: 'image',
        image_url: img,
        alt_text: 'article thumbnail'
      };
    }

    blocks.push({
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `📅 ${new Date(article.published_at || Date.now()).toLocaleString()} • Sent via *FeedOmeter*`
        }
      ]
    });

    return {
      text: `⚡ Feed Alert [${ruleName}]: ${title}`,
      blocks
    };
  }

  /**
   * Builds Slack Block Kit payload for a scheduled digest batch
   */
  static buildDigestPayload(articles, digestName = 'Daily Intelligence Briefing', scheduleLabel = 'Daily Digest') {
    const count = articles.length;
    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `📰 ${digestName}`,
          emoji: true
        }
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `📅 *Schedule:* ${scheduleLabel} • *Articles:* ${count} • Generated by *FeedOmeter*`
          }
        ]
      },
      { type: 'divider' }
    ];

    if (count === 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: '_No new matching articles syndicated during this digest period._'
        }
      });
    } else {
      const displayList = articles.slice(0, 15);
      displayList.forEach((art, idx) => {
        const title = (art.title || 'Untitled Article').replace(/[<>&]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[c]));
        const url = art.url || art.link || 'https://feedometer.com';
        const source = art.source_name || art.source || art.domain || 'News Source';
        const snippet = (art.description || art.snippet || '').replace(/<[^>]+>/g, '').trim().slice(0, 160);
        const img = art.image_url || art.image || art.og_image || art.lead_image_url || '';

        const section = {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: `*<${url}|${idx + 1}. ${title}>*\n*${source}* • ${snippet ? `_${snippet}..._` : ''}`
          }
        };

        if (img && (img.startsWith('http://') || img.startsWith('https://'))) {
          section.accessory = {
            type: 'image',
            image_url: img,
            alt_text: 'article thumbnail'
          };
        }

        blocks.push(section);
      });

      if (articles.length > 15) {
        blocks.push({
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `_...and ${articles.length - 15} more articles matching your filters._`
            }
          ]
        });
      }
    }

    blocks.push({ type: 'divider' });

    return {
      text: `📰 ${digestName} — ${count} articles matched`,
      blocks
    };
  }

  /**
   * Dispatches payload to target Slack webhook URL
   */
  static async send(webhookUrl, payload) {
    const startTime = Date.now();
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });
    const durationMs = Date.now() - startTime;
    return {
      ok: res.ok,
      status: res.status,
      statusText: res.statusText,
      durationMs
    };
  }
}
